"use client";

import React from "react";
import { AlertTriangle } from "lucide-react";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { useTranslations } from "next-intl";


function DisclaimerPage() {
  const t = useTranslations('disclaimer');
  return (
    <PublicLayout>
      <div className="py-24 px-6 max-w-4xl mx-auto">
        <div className="text-center mb-16">
          <div className="flex items-center justify-center gap-3 mb-4">
            <AlertTriangle className="w-8 h-8 text-yellow-500" />
            <h1 className="text-4xl font-bold">Disclaimer</h1>
          </div>
          <p className="text-[var(--text-secondary)]">{t('importantLegalFinancialDisclaimers')}</p>
        </div>

        <div className="prose prose-invert prose-lg max-w-none space-y-8">
          <div className="p-6 bg-red-500/10 border border-red-500/30 rounded-xl mb-8">
            <h2 className="text-xl font-bold text-red-400 mb-3 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5" />
              Investment Risk Warning
            </h2>
            <p className="text-[var(--text-secondary)] leading-relaxed">
              Trading and investing in financial markets involves substantial risk of loss and is not suitable for all investors. 
              You should carefully consider your financial situation and risk tolerance before using any analysis or recommendations 
              generated by FinanceAI. Past performance does not guarantee future results.
            </p>
          </div>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">{t('noFinancialAdvice')}</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>FinanceAI is a technology platform that provides analytical tools and information. We do not provide:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Investment advice or recommendations</li>
                <li>Tax, legal, or accounting advice</li>
                <li>Personalized financial planning services</li>
                <li>Trading signals or market timing guidance</li>
                <li>Portfolio management services</li>
              </ul>
              <p className="font-semibold">All content generated by our AI agents is for informational and educational purposes only.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">AI-Generated Content Limitations</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>Our AI agents analyze publicly available information and generate reports based on their training. However:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI analysis may contain errors, biases, or inaccuracies</li>
                <li>Market conditions change rapidly and analysis may become outdated</li>
                <li>AI models cannot predict future market movements with certainty</li>
                <li>Analysis is based on historical data and patterns that may not repeat</li>
                <li>External factors not captured in data can significantly impact markets</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">{t('dataSourcesAndAccuracy')}</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>While we strive to use reliable data sources, we cannot guarantee:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>The accuracy, completeness, or timeliness of third-party data</li>
                <li>That all relevant information has been considered in analysis</li>
                <li>That data feeds are free from errors or delays</li>
                <li>That analysis reflects the most current market conditions</li>
              </ul>
              <p>Always verify important information through multiple independent sources.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">Regulatory Compliance</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>FinanceAI Inc. is not:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>A registered investment advisor (RIA)</li>
                <li>A broker-dealer or financial institution</li>
                <li>Regulated by the SEC, FINRA, or other financial authorities</li>
                <li>Licensed to provide investment advice in any jurisdiction</li>
              </ul>
              <p>Users are responsible for ensuring compliance with all applicable laws and regulations in their jurisdiction.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">{t('marketRisks')}</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>Financial markets are subject to various risks including but not limited to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>{t('marketRisk')}</strong> Overall market movements affecting all securities</li>
                <li><strong>Volatility Risk:</strong> Rapid and significant price fluctuations</li>
                <li><strong>Liquidity Risk:</strong> Difficulty buying or selling securities at desired prices</li>
                <li><strong>Credit Risk:</strong> Risk of default by issuers or counterparties</li>
                <li><strong>Currency Risk:</strong> Exchange rate fluctuations for international investments</li>
                <li><strong>Regulatory Risk:</strong> {t('changesInLawsAndRegulations')}</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">Professional Consultation</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>Before making any investment decisions, you should consult with qualified professionals:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Licensed financial advisors for investment guidance</li>
                <li>Tax professionals for tax implications</li>
                <li>Legal counsel for regulatory compliance</li>
                <li>Accountants for financial planning</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">Limitation of Liability</h2>
            <div className="text-[var(--text-secondary)] space-y-4">
              <p>By using FinanceAI, you acknowledge and agree that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You use our services at your own risk</li>
                <li>We are not liable for any investment losses or damages</li>
                <li>You will not hold us responsible for market performance</li>
                <li>Our liability is limited to the amount you paid for our services</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-[var(--text-primary)]">{t('contactInformation')}</h2>
            <div className="text-[var(--text-secondary)]">
              <p>For questions about this disclaimer or our services:</p>
              <div className="mt-4 p-4 bg-[var(--bg-panel)] border border-[var(--border-color)] rounded-lg">
                <p><strong>{t('email')}</strong> legal@financeai.com</p>
                <p><strong>{t('address')}</strong> FinanceAI Inc., 123 Wall Street, New York, NY 10005</p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </PublicLayout>
  );
}

export default DisclaimerPage;
